### PR TITLE
Cb news form

### PR DESCRIPTION
**Pull request by CalBoyt**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

News Data Needed:
Add news objects to your json database file for testing:

  "news": [
    {
      "title": "Wormholes Allow Information to Escape Black Holes",
      "synopsis": "Check out this recent discovery about workholes",
      "url": "https://www.quantamagazine.org/newfound-wormhole-allows-information-to-escape-black-holes-20171023/",
      "timestamp": 1697654027085,
      "id": 9
    },
    {
      "title": "House Votes to Outlaw Black Holes",
      "synopsis": "example",
      "url": "https://wwwexample",
      "timestamp": 1697654074005,
      "id": 10
    }  
  ]

- [x] Button to add new article and a listing of previous news articles should appear in DOM
- [x] When New Article button is clicked, form should appear with 3 fields 
- [x] When all the form fields are completed and Save Article button is clicked, the new article should be added to list of articles 
- [x] If any form fields are blank and Save Article button is clicked, a message should appear, telling you to complete all fields
- [x] When Delete button next to an article is clicked, the selected article should be deleted from the database 

# Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings or errors
- [x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by loganvanmeter** [comment]
Everything tested as it should for me.

**Comment by loganvanmeter** [comment]
All the tests worked for me. Something to think about. you might want the article URL to return a blank hyperlink for the news article

**Comment by cm19982023** [comment]
Functional items :)

**Review by loganvanmeter — DISMISSED** [review]
This looks great!

**Review by cm19982023 — DISMISSED** [review]
new additions functioned on my end. only thing was log out button was duplicated. this could be user error on my end. good job!

**Review by loganvanmeter — APPROVED** [review]
This looks like what we just did

**Pull request merged**
